#!/bin/bash
python maskrcnn_test.py --anno LLJ --mode rad
python maskrcnn_test.py --anno LLJ --mode sat
python maskrcnn_test.py --anno W_SNOW --mode sat
python maskrcnn_test.py --anno E_SNOW --mode sat
python maskrcnn_test.py --anno WET_SN --mode sat
python maskrcnn_test.py --anno CUM_SN --mode sat
python maskrcnn_test.py --anno COLD_FRONT --mode sat
python maskrcnn_test.py --anno WARM_FRONT --mode sat
python maskrcnn_test.py --anno OCC_FRONT --mode sat
python maskrcnn_test.py --anno H_POINT --mode sat
python maskrcnn_test.py --anno L_POINT --mode sat
python maskrcnn_test.py --anno HLJ --mode sat
python maskrcnn_test.py --anno TYPOON --mode sat
python maskrcnn_test.py --anno R_START --mode sat
python maskrcnn_test.py --anno R_STOP --mode sat
python maskrcnn_test.py --anno RA_SN --mode sat
python maskrcnn_test.py --anno HAIL --mode sat
python maskrcnn_test.py --anno W_SNOW --mode rad
python maskrcnn_test.py --anno E_SNOW --mode rad
python maskrcnn_test.py --anno WET_SN --mode rad
python maskrcnn_test.py --anno CUM_SN --mode rad
python maskrcnn_test.py --anno COLD_FRONT --mode rad
python maskrcnn_test.py --anno WARM_FRONT --mode rad
python maskrcnn_test.py --anno OCC_FRONT --mode rad
python maskrcnn_test.py --anno H_POINT --mode rad
python maskrcnn_test.py --anno L_POINT --mode rad
python maskrcnn_test.py --anno HLJ --mode rad
python maskrcnn_test.py --anno TYPOON --mode rad
python maskrcnn_test.py --anno R_START --mode rad
python maskrcnn_test.py --anno R_STOP --mode rad
python maskrcnn_test.py --anno RA_SN --mode rad
python maskrcnn_test.py --anno HAIL --mode rad